### PR TITLE
perf: Adjust function RemoveFilteredPolicy

### PR DESCRIPTION
**Pull request by Edmond-J-A**
Adjust function RemoveFilteredPolicy ,I think it will remove Policy more efficiently in this way.
Signed-off-by: Edmond <edomondja@gmail.com>

### CODE REVIEW

**Comment by Edmond-J-A** [comment]
@hsluoyz plz review

**Review by closetool — APPROVED** [review]
Not that efficient, but more clear

**Comment by hsluoyz** [comment]
@Edmond-J-A this is at most a "fix" instead of "feat"

**Comment by Edmond-J-A** [comment]
> @Edmond-JA这最多是一个“修复”而不是“壮举”，最好使用诸如“perf”之类的不会触发新版本的东西，因为它太琐碎了。

Got it,changed.

**Pull request merged**
