### PR TITLE
docs: fix typos in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by HollowMan6**
* un -> an
* up to date -> up-to-date

### CODE REVIEW

**Comment by hsluoyz** [comment]
@HollowMan6 thanks for contributing!

**Comment by hsluoyz** [comment]
@HollowMan6 can you fix semantic PR?

image

**Comment by HollowMan6** [comment]
> @HollowMan6 can you fix semantic PR?
> 
> image

@hsluoyz done!

**Comment by nodece** [comment]
@HollowMan6 great!

**Pull request merged**
