### PR TITLE
feat: add Extracting variables from paths(#673)

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>
add new feature

Fix: https://github.com/casbin/casbin/issues/673

### CODE REVIEW

**Comment by hsluoyz** [comment]
@closetool the current code looks ok to me. Can you add some tests for the `keyGet()` and `keyGet2()` functions?

**Comment by closetool** [comment]
Are these tests enough

**Comment by hsluoyz** [comment]
@fr3fou please review.

**Comment by fr3fou** [comment]
LGTM

**Comment by hsluoyz** [comment]
kudos to @closetool !

**Pull request merged**
