### PR TITLE
fix: add explain index on allow

### PR DESCRIPTION
**Pull request by PhilippSeitz**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@PhilippSeitz please fix the semantic PR error:

image

**Comment by GopherJ** [comment]
Seems since certain commit we have only one explainIndex available, but it's not the case for `some(p.eft == allow) && !some(p.eft == deny)` effect.

**Comment by GopherJ** [comment]
we have lost this pr: https://github.com/casbin/casbin/pull/472

**Comment by nodece** [comment]
We have planed to support the feature on v3, so close the PR.

**Pull request closed without merging**
