### PR TITLE
fix: should remove escaped double quotes

### PR DESCRIPTION
**Pull request by GopherJ**
Signed-off-by: Cheng JIANG <jiang.cheng@vip.163.com>

Try Fix: #518

### CODE REVIEW

**Comment by GopherJ** [comment]
I believe this will still not fix issue, because it'll probably split by "," which breaks things

**Comment by hsluoyz** [comment]
I like the lint part.. But the trim call is not fixing the issue. Can I ask to keep the lint part only?

**Comment by GopherJ** [comment]
I believe it already fixed the issue

**Comment by hsluoyz** [comment]
Oh. I missed the 2nd commit. Never mind.

**Pull request merged**
