### PR TITLE
feat: add batch methods for update grouping policies

### PR DESCRIPTION
**Pull request by zsh1995**
Add Batch operations for `UpdateGroupingPolicy` and `UpdateNamedGroupingPolicy`.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@zsh1995 plz fix:

image

**Comment by zsh1995** [comment]
@hsluoyz fix done.

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @seriouszyx @fabian4 plz review

**Review by fabian4 — APPROVED** [review]
LGTM

**Comment by hsluoyz** [comment]
@zsh1995 thanks for contribution! Plz also add them to docs: https://github.com/casbin/casbin-website

**Pull request merged**
