### PR TITLE
feat: Added batch update watcher methods

### PR DESCRIPTION
**Pull request by h7kanna**
Fix: https://github.com/casbin/redis-watcher/issues/7

Added batch update methods to watcher interface to complete the implementation of redis watcher for https://github.com/casbin/redis-watcher/issues/7

### CODE REVIEW

**Comment by hsluoyz** [comment]
@closetool plz review.

**Review by closetool — APPROVED** [review]
LGTM

**Review by tangyang9464 — APPROVED** [review]
LGTM

**Comment by h7kanna** [comment]
Hi, Thank you. will continue with PR for my changes to redis-watcher once this merged.

**Pull request merged**
