### PR TITLE
feat: allow permissions management to use additional p-types

### PR DESCRIPTION
**Pull request by Nekotoxin**
synced a new feature from pycasbin
see at  [pycasbin: add named policy](https://github.com/casbin/pycasbin/pull/256)

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@Nekotoxin use feat instead of fix

**Comment by Nekotoxin** [comment]
> @Nekotoxin use feat instead of fix

changed

**Review by tangyang9464 — APPROVED** [review]
lgtm

**Pull request merged**
