### PR TITLE
fix: add support to use '*' in keymatch5 utils

### PR DESCRIPTION
**Pull request by MkDierz**
Fix: https://github.com/casbin/casbin/issues/1176

### CODE REVIEW

**Comment by hsluoyz** [comment]
@PokIsemaine plz review

**Comment by PokIsemaine** [comment]
@MkDierz Thanks for your contribution, the basic implementation and testing are fine, it would be even better if you can help improve the comments of KeyMatch5.
``` golang
// KeyMatch determines whether key1 matches the pattern of key2 and ignores the parameters in key2.
// For example, "/foo/bar?status=1&type=2" matches "/foo/bar"
func KeyMatch5(key1 string, key2 string) bool {
}
```
For example：
* fix `KeyMatch` -> `KeyMatch5`
* add more examples
  * You can choose some examples from your test
  * Add an example of matching failure

You can refer to the comments of KeyMatch4
```golang
// KeyMatch4 determines whether key1 matches the pattern of key2 (similar to RESTful path), key2 can contain a *.
// Besides what KeyMatch3 does, KeyMatch4 can also match repeated patterns:
// "/parent/123/child/123" matches "/parent/{id}/child/{id}"
// "/parent/123/child/456" does not match "/parent/{id}/child/{id}"
// But KeyMatch3 will match both.
```

**Comment by MkDierz** [comment]
Hi thanks for the review, ill do it ASAP.

**Comment by PokIsemaine** [comment]
@MkDierz You can try to use `push -f` to remove commits that do not meet the requirements
image

**Comment by MkDierz** [comment]
> @MkDierz You can try to use `push -f` to remove commits that do not meet the requirements image

i'm sorry for the trouble
i'll do it next time thanks

**Pull request merged**
