### PR TITLE
feat: add policy length check in LoadPolicyLine

### PR DESCRIPTION
**Pull request by tangyang9464**
Fix: https://github.com/casbin/casbin/issues/1016

Signed-off-by: tangyang9464 <tangyang9464@163.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464 @qingwave what's the benchmark downgrade? We prefer to add checks to compile-time instead of run-time mostly for performance reason.

**Comment by tangyang9464** [comment]
> @tangyang9464 @qingwave what's the benchmark downgrade? We prefer to add checks to compile-time instead of run-time mostly for performance reason.

@hsluoyz Maybe it's not a good idea. The length has been checked elsewhere. If the performance is degraded, then this PR is useless

**Comment by tangyang9464** [comment]
@hsluoyz The current implementation is that invalid policy may exist when loading the model, and the length will be checked only when the policy is used, such as the enforce method. So it looks more efficient than checking from the beginning of the loading policy

**Comment by hsluoyz** [comment]
@tangyang9464 I agree, we don't need to add duplicated checks. Then we don't need this.

**Comment by sagilio** [comment]
@tangyang9464 @hsluoyz  Do we have any existing tests to see the rate of performance degradation because of this PR?
I think if we check the length in any edit policy API, we will need not check it at `Enforce` func. 
And If add a check in the right place, there will have almost no impact on performance. like here:

```go
// HasPolicy determines whether a model has the specified policy rule.
func (model Model) HasPolicy(sec string, ptype string, rule []string) bool {
	assertion := model[sec][ptype]
	if len(assertion.Tokens) != len(rule) {
		return false
	}
	_, ok := assertion.PolicyMap[strings.Join(rule, DefaultSep)]
	return ok
}
```

**Comment by hsluoyz** [comment]
@sagilio see https://casbin.org/docs/en/benchmark and xxx_b_test.go at: https://github.com/casbin/casbin#benchmarks

**Comment by sagilio** [comment]
@hsluoyz I see, but the changes in this PR don't seem to be covered by any of the tests in `xxx_b_test.go`,
and the benchmark result in each CI run may also max deviation of about 20%. 
The result in the docs seems a very old version.

**Comment by hsluoyz** [comment]
@sagilio then we need to add more tests to cover this case. And we can run multiple rounds and use average number to reduce the randomness. @JalinWang actually we want to build a new benchmark system to list all Casbin related benchmark data there.

**Comment by sagilio** [comment]
@hsluoyz The reason for the deviation of each ci test is that the environment(CPU) is not fixed. There is only a little difference between the same environments.

Casbin.NET's result will output the environment information.
image
image

**Comment by hsluoyz** [comment]
@sagilio good point. We will build our own CI anyway.

**Comment by hsluoyz** [comment]
We don't do a lot of input checks to sacrifice the performance. The user is responsible for input validity.

**Pull request closed without merging**
