### PR TITLE
feat: add a rule of effect "Allow-override"

### PR DESCRIPTION
**Pull request by ticktap**
fix: #496

### CODE REVIEW

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics please review.

**Comment by hsluoyz** [comment]
@ticktap why don't use priority model?

**Comment by ticktap** [comment]
> @ticktap why don't use priority model?

it can not allow when I omit allow policy, priority default result is false.

**Comment by nodece** [comment]
@ticktap I think `priority(p_eft) || allow` can meet your need?

**Comment by hsluoyz** [comment]
@ticktap you can add a policy to allow all, put it at the last of the list.

**Comment by ticktap** [comment]
> @ticktap you can add a policy to allow all, put it at the last of the list.

It worked for me. But I think it is necessary to add "Allow-override".

**Comment by nodece** [comment]
@hsluoyz  Could you review the PR?

**Comment by hsluoyz** [comment]
@ticktap please fix the checks:

image

**Comment by nodece** [comment]
@hsluoyz if you are approved, I will merge it to master.

**Comment by hsluoyz** [comment]
@nodece please let @ticktap fix the checks:

image

**Comment by ticktap** [comment]
Sorry, I'm not sure how to fix these checks. @hsluoyz any tips?

**Comment by hsluoyz** [comment]
@ticktap see: https://github.com/zeke/semantic-pull-requests

**Comment by nodece** [comment]
apologize, so later that merge the PR, your work is great.

**Comment by hsluoyz** [comment]
@ticktap @nodece please add this new effect to our docs:

1. https://casbin.org/docs/en/supported-models#examples
2. https://casbin.org/docs/en/syntax-for-models#policy-effect

**Pull request merged**
