### PR TITLE
fix: GetPermissionsForUser panics on empty list of domains

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <4closetool3@gmail.com>

Fix: #799

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Gilthoniel plz review.

**Comment by hsluoyz** [comment]
@Sagilio plz review.

**Review by Sagilio — APPROVED** [review]
https://github.com/casbin/casbin/blob/beedee2c0f86039b927863a4e9931e91421456a3/internal_api.go#L364

I think we can use the existing API to get the domain index.

**Comment by closetool** [comment]
> I think we can use the existing API to get the domain index.
> https://github.com/casbin/casbin/blob/beedee2c0f86039b927863a4e9931e91421456a3/internal_api.go#L364

@Sagilio  fixed

**Pull request merged**
