### PR TITLE
feat: add sync cache and synced cached enforcer

### PR DESCRIPTION
**Pull request by SnowWarri0r**
Fix: https://github.com/casbin/casbin/issues/1214

I tried to add a sync cache and then add SyncedCachedEnforcer.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@SnowWarri0r fix all CI errors:

image

**Comment by SnowWarri0r** [comment]
in my local,i can pass all test,i just changed examples/rbac_model.conf from CRLF to LF.
my go version is 1.18.4
image

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@SnowWarri0r 
image

You can try to refactor your code.
image

**Comment by PokIsemaine** [comment]
> in my local,i can pass all test,i just changed examples/rbac_model.conf from CRLF to LF. my go version is 1.18.4 image
CRLF and LF can be solved by setting up your git or editor.

When testing concurrently, you can consider repeating the test multiple times (or even looping infinitely until an error is reported when testing locally) to reduce the possibility of accidental success. You can refer to SyncedEnforcer's test.

**Comment by SnowWarri0r** [comment]
> > in my local,i can pass all test,i just changed examples/rbac_model.conf from CRLF to LF. my go version is 1.18.4 image
> 
> 1. CRLF and LF can be solved by setting up your git or editor.
> 2. When testing concurrently, you can consider repeating the test multiple times (or even looping infinitely until an error is reported when testing locally) to reduce the possibility of accidental success. You can refer to SyncedEnforcer's test.

i changed SyncedCachedEnforcer internal Enforcer to SyncedEnforcer.
then I tried to run testing, had been starting 1000000 goroutines and then had passed.
about refactoring, i extract getKey method to function.

**Comment by SnowWarri0r** [comment]
force-pushed to fix commit message

**Comment by SnowWarri0r** [comment]
@hsluoyz

**Comment by hsluoyz** [comment]
@yugant007 @PokIsemaine plz review

**Comment by PokIsemaine** [comment]
@SnowWarri0r 
Thanks for your work, the basic functionality and tests are well done.

@hsluoyz 
Regarding "code climate", I think the relevant threshold may be a little stricter, you may consider manually skipping "code climate" to merge this PR (of course, this needs to be considered carefully, because it may cause a bad start)
Please let @SnowWarri0r  know if you think refactoring is still needed

**Comment by hsluoyz** [comment]
"code climate" is optional

**Comment by hsluoyz** [comment]
@SnowWarri0r plz join the QQ group: 714894552

**Comment by SnowWarri0r** [comment]
> @SnowWarri0r plz join the QQ group: 714894552

ok

**Pull request merged**
