### PR TITLE
fix: custom RoleManager lost

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

Fix: #820

### CODE REVIEW

**Comment by closetool** [comment]
@hsluoyz @nodece plz review

**Comment by natsukagami** [comment]
I think even with this fix, if I call `enforcer.BuildRoleLinks`, or have `AutoBuildRoleLinks` on:
- `buildRoleLinks` is called, which makes ...
- `initRmMap` will still be called, ...
https://github.com/casbin/casbin/blob/09b29f316fac71bb7b907feb8ab9e31a206c41e6/enforcer.go#L442
- which still overrides all my `RoleManager`s in `e.rmMap` with `defaultrolemanager.NewRoleManager`:
https://github.com/casbin/casbin/blob/09b29f316fac71bb7b907feb8ab9e31a206c41e6/enforcer.go#L396-L400

**Comment by dahu33** [comment]
Would be nice to also add a test.

**Comment by hsluoyz** [comment]
Wait for: https://github.com/casbin/casbin/issues/820#issuecomment-865914013

**Comment by closetool** [comment]
@natsukagami Ok, I'll find a better way.

**Comment by closetool** [comment]
@hsluoyz Ok

**Pull request closed without merging**
