### PR TITLE
fix: Set the correct value for logExplains

### PR DESCRIPTION
**Pull request by linzworld**
Signed-off-by: 2448974318@qq.com
fix: #889

### CODE REVIEW

**Comment by linzworld** [comment]
This is the result of the TestEnforceExLog function in enforce_test.go, mainly to fix the comparison between before and after errors.

The following is the result of the original error: 
image

After fixing the bug, here is the correct output:
image

**Comment by hsluoyz** [comment]
@tangyang9464 plz review

**Review by tangyang9464 — APPROVED** [review]
LGTM

**Review by sagilio — APPROVED** [review]
LGTM

**Pull request merged**
