### PR TITLE
feat: add GetImplicitUsersForResource() API

### PR DESCRIPTION
**Pull request by PokIsemaine**
fix: https://github.com/casbin/casbin/issues/1241

### CODE REVIEW

**Comment by hsluoyz** [comment]
@erickhgm plz review

**Comment by erickhgm** [comment]
Looks good to me! 💯 

I don't know much about the code base to check if something can be improved. However, I can test a pre-release version before the merge if you want.

**Comment by hsluoyz** [comment]
@erickhgm yes, please test the code in this PR to see if it is expected

**Comment by erickhgm** [comment]
> @erickhgm yes, please test the code in this PR to see if it is expected

It's working!

**Comment by hsluoyz** [comment]
@PokIsemaine plz add this new API to docs

**Pull request merged**
