### PR TITLE
feat: Improve logger

### PR DESCRIPTION
**Pull request by kocoler**
Fix: https://github.com/casbin/casbin/issues/234

Improve the logger function.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@kocoler fix CI.

**Comment by kocoler** [comment]
@hsluoyz already fixed.

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics please review.

**Comment by nodece** [comment]
@kocoler I suggest that you add an EnforceLog interface to the log folder, you don't need to change the currently log, EnforceLog only records enforce log. 

@hsluoyz what do you think?

**Comment by hsluoyz** [comment]
I think we should have a clear idea about why we are refactoring the logging.

From my opinion, we already have a logger interface, and an default logger that implements the logger. Next we should focus on how to implement other loggers that use the No.1, No.2 open-source Golang loggers. In such process, we may found places to improve inside our logger interface. Then we iterate to improve it. I think this is how the entire process works.

**Comment by nodece** [comment]
@hsluoyz sounds great.  It is important that improve the currently log interface. A good idea that provides different level log.

**Pull request merged**
