### PR TITLE
Support pattern function in 3rd args of g

### PR DESCRIPTION
**Pull request by dovics**
https://github.com/casbin/casbin/issues/337
I have finished the requirement of this issue, and I want to add the pattern function in p, now we can use  syntax like this
```
p, admin, domain1, data1, read
p, admin, domain1, data1, write
p, admin, *, data2, read
p, admin, *, data2, write

g, alice, admin, *
g, bob, admin, domain2
```

### CODE REVIEW

**Comment by hsluoyz** [comment]
Please fix CI.

**Comment by dovics** [comment]
This is my first time to pull request, I'm not very familiar with the operation process, I'm sorry for the problem

**Comment by nodece** [comment]
@dovics We need a bit time for pr.

**Comment by nodece** [comment]
@hsluoyz Can you give me a bit time to review? It looks good.

**Comment by nodece** [comment]
@dovics  
Please add tests case  in https://github.com/casbin/casbin/blob/master/rbac/default-role-manager/role_manager_test.go. Make the RoleManager interface works fine.

**Comment by nodece** [comment]
At the moment, enforcer works fine, but manager_api is not working.  
We should add test cases for the manager_api.

**Comment by dovics** [comment]
I found a bug, if you use * when querying permissions, the result will be wrong, such as
```
//                     domain1:g1                    domain2:g2
//		              | 		            	|
//		       domain1:u1    	             domain2:u2
rm.HasLink(u1, g1, *)   // true
rm.HasLink(u1, g2, *). // false
```
So I forbid using * when querying，Is there a better solution？

**Comment by nodece** [comment]
Hi @hsluoyz @dovics,

My point of view:
-  default RoleManager should not support matching.  
- default RoleManager data structure  can not support pattern function in 3rd arges of g.    
- re-implementation [RoleManager](https://github.com/casbin/casbin/blob/master/rbac/role_manager.go) for support the domain matching is better solution by .

Thanks for contribution @dovics .

**Comment by dovics** [comment]
@nodece I will find time to do it

**Comment by hsluoyz** [comment]
@dovics please stop repeating messages in commits like this:

image

Squash them for appending.

**Comment by dovics** [comment]
Sorry for the mistake I made, thank you for your correction

I have completed the basic functions in my own repositories(https://github.com/dovics/domain-role-manager),can you take the time to look at it for me?

I want to continue adding test cases and adding some other functions like IPMatch or RegexMatch etc.

**Comment by nodece** [comment]
Sorry @dovics  for reply late.

Your implement is good. Users can put `https://github.com/dovics/domain-role-manager` to own project.

**Comment by hsluoyz** [comment]
@dovics we had a discussion about it and finally decided to merge the functionality "Support pattern function in 3rd args of g" into this repo. Can you start a new PR for the merging process?

**Comment by dovics** [comment]
Ok i will finish it this weekend

**Pull request closed without merging**
