### PR TITLE
fix: seamless role manager replace

### PR DESCRIPTION
**Pull request by alikhanz**
Continue of this PR:
https://github.com/casbin/casbin/pull/975

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@alikhanz ``Copy`` can simply call ``NewRoleManger`` to return an initialized ``rm``, and then it doesn't have to call ``rm.Clear``.

**Comment by hsluoyz** [comment]
@alikhanz plz fix:

image

**Comment by alikhanz** [comment]
> @alikhanz `Copy` can simply call `NewRoleManger` to return an initialized `rm`, and then it doesn't have to call `rm.Clear`. Then mabye should rename Copy as CopyByStructure or some other unambiguous name.

Because why?

**Comment by tangyang9464** [comment]
> > @alikhanz `Copy` can simply call `NewRoleManger` to return an initialized `rm`, and then it doesn't have to call `rm.Clear`. Then mabye should rename Copy as CopyByStructure or some other unambiguous name.
> 
> Because why?
@alikhanz Copying all data incurs unnecessary overhead

**Comment by alikhanz** [comment]
Sorry. My bad. 
Im not upgraded casbin-server, and catched bug that was already fixed here:
https://github.com/casbin/casbin-server/commit/64d90d05d7bb1ff7ec54418cd98477b4f7f74509

Close this PR? Or i can fix according to comments.

**Comment by alikhanz** [comment]
@hsluoyz

**Pull request closed without merging**
