### PR TITLE
feat: add CacheableParam interface

### LINKED ISSUE #924: [Feature] Cacheable ABAC params
Hello!
I want to optimize `enforce` requests, and trying to use `CachedEnforcer`, but ABAC parameters come as `AbacAttrList` structure here: https://github.com/casbin/casbin/blob/master/enforcer_cached.go#L148

https://github.com/casbin/casbin/blob/1f2210076100a0b10e9b820b82eaf15550e7c2c8/enforcer_cached.go#L145-L156

As a result, the request is not cached. Im trying to add `CacheableParam` interface, and implementation. 

It's my first contribution in golang project, so I am open to your questions and criticism.

### PR DESCRIPTION
**Pull request by alikhanz**
Fix: https://github.com/casbin/casbin/issues/924

### CODE REVIEW

**Comment by hsluoyz** [comment]
lgtm

**Comment by alikhanz** [comment]
@hsluoyz can we release this merge in v2? I need this for continue my work

**Comment by hsluoyz** [comment]
Hi @alikhanz the GitHub actions CI error has blocked the auto semantic-release. Can you take a look at why? https://github.com/casbin/casbin/runs/4414726653?check_suite_focus=true

**Comment by alikhanz** [comment]
> Hi @alikhanz the GitHub actions CI error has blocked the auto semantic-release. Can you take a look at why? https://github.com/casbin/casbin/runs/4414726653?check_suite_focus=true

Hello!
PR with fix here: https://github.com/casbin/casbin/pull/928

**Comment by hsluoyz** [comment]
@alikhanz v2.40.0 released: https://github.com/casbin/casbin/releases/tag/v2.40.0

**Pull request merged**
