### PR TITLE
docs: updated broken links in README

### PR DESCRIPTION
**Pull request by r4wand**
Updated the broken links

### CODE REVIEW

**Comment by hsluoyz** [comment]
@r4wand plz sign:

image

**Comment by r4wand** [comment]
> @r4wand plz sign:
> 
> image

Just did.

**Comment by hsluoyz** [comment]
@r4wand thanks! Can you also update other languages like: https://github.com/casbin/jcasbin ?

**Comment by r4wand** [comment]
> @r4wand thanks! Can you also update other languages like: https://github.com/casbin/jcasbin ?

Sure. I'll update all that I can today.

**Comment by hsluoyz** [comment]
https://casbin.org/ here listed all languages

image

**Pull request merged**
