### PR TITLE
Replace `sync.Mutex` with `sync.RWMutex` for CachedEnforcer 

### PR DESCRIPTION
**Pull request by jszwedko**
`sync.Map` appears to fit better here as the current implementation serializes any writes to the map even though they are typically writing separate keys (and typically only ever a given key, once). Using `sync.Map` reduces contention on this mutex.

From https://golang.org/pkg/sync/#Map
> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

I think this use case fits the first well.

Running the added benchmark locally, I saw a roughly 40% improvement.

Before:

```
go test -cpu 4 -bench BenchmarkCachedRBACModelMediumParallel
2019/04/25 13:35:27 Start automatically load policy     
2019/04/25 13:35:27 Stop automatically load policy
2019/04/25 13:35:27 Start automatically load policy
2019/04/25 13:35:27 Model:
2019/04/25 13:35:27 p.p: sub, obj, act        
2019/04/25 13:35:27 e.e: some(where (p_eft == allow))
2019/04/25 13:35:27 m.m: r_sub == p_sub && r_obj == p_obj && r_act == p_act     
2019/04/25 13:35:27 r.r: sub, obj, act
2019/04/25 13:35:27 Policy:                   
2019/04/25 13:35:27 p: sub, obj, act: [[alice data1 read] [bob data2 write]]
2019/04/25 13:35:27 Request: alice, data1, read ---> true
2019/04/25 13:35:27 Request: alice, data1, write ---> false                                                                                                                                                        
2019/04/25 13:35:27 Request: alice, data2, read ---> false
2019/04/25 13:35:27 Request: alice, data2, write ---> false
2019/04/25 13:35:27 Request: bob, data1, read ---> false
2019/04/25 13:35:27 Request: bob, data1, write ---> false
2019/04/25 13:35:27 Request: bob, data2, read ---> false
2019/04/25 13:35:27 Request: bob, data2, write ---> true
2019/04/25 13:35:27 Stop automatically load policy   
goos: linux                                                                
goarch: amd64              
pkg: github.com/casbin/casbin                                               
BenchmarkCachedRBACModelMediumParallel-4         5000000               359 ns/op
PASS                                                       
ok      github.com/casbin/casbin        5.137s    
```

After:

```
go test -cpu 4 -bench BenchmarkCachedRBACModelMediumParallel
2019/04/25 13:35:11 Start automatically load policy
2019/04/25 13:35:11 Stop automatically load policy                              
2019/04/25 13:35:11 Start automatically load policy
2019/04/25 13:35:11 Model:
2019/04/25 13:35:11 r.r: sub, obj, act
2019/04/25 13:35:11 p.p: sub, obj, act
2019/04/25 13:35:11 e.e: some(where (p_eft == allow))
2019/04/25 13:35:11 m.m: r_sub == p_sub && r_obj == p_obj && r_act == p_act
2019/04/25 13:35:11 Policy:
2019/04/25 13:35:11 p: sub, obj, act: [[alice data1 read] [bob data2 write]]
2019/04/25 13:35:11 Request: alice, data1, read ---> true
2019/04/25 13:35:11 Request: alice, data1, write ---> false
2019/04/25 13:35:11 Request: alice, data2, read ---> false
2019/04/25 13:35:11 Request: alice, data2, write ---> false
2019/04/25 13:35:11 Request: bob, data1, read ---> false
2019/04/25 13:35:11 Request: bob, data1, write ---> false
2019/04/25 13:35:11 Request: bob, data2, read ---> false
2019/04/25 13:35:11 Request: bob, data2, write ---> true
2019/04/25 13:35:11 Stop automatically load policy
goos: linux
goarch: amd64
pkg: github.com/casbin/casbin
BenchmarkCachedRBACModelMediumParallel-4        10000000               220 ns/op
PASS
ok      github.com/casbin/casbin        5.434s
```

I only added a parallel benchmark of BenchmarkCachedRBACModelMedium for now, but
we could opt to instead replace existing benchmarks with parallel benchmarks to show how the enforcer behaves when accessed from multiple goroutines.

### CODE REVIEW

**Comment by vtolstov** [comment]
Can you try test also, if sync.Mutex replaces with sync.RWMutex? as i read from other projects, sync.Map not recommended to use and using own locking with RWMutex gave more performance

**Comment by jszwedko** [comment]
@vtolstov good thought, it looks like the locking on read contention is the main culprit.

With this diff:

```diff
diff --git a/enforcer_cached.go b/enforcer_cached.go
index fffc834..14cea5e 100644
--- a/enforcer_cached.go
+++ b/enforcer_cached.go
@@ -23,7 +23,7 @@ type CachedEnforcer struct {
        *Enforcer
        m           map[string]bool
        enableCache bool
-       locker      *sync.Mutex
+       locker      *sync.RWMutex
 }

 // NewCachedEnforcer creates a cached enforcer via file or DB.
@@ -32,7 +32,7 @@ func NewCachedEnforcer(params ...interface{}) *CachedEnforcer {
        e.Enforcer = NewEnforcer(params...)
        e.enableCache = true
        e.m = make(map[string]bool)
-       e.locker = new(sync.Mutex)
+       e.locker = new(sync.RWMutex)
        return e
 }

@@ -57,13 +57,16 @@ func (e *CachedEnforcer) Enforce(rvals ...interface{}) bool {
                }
        }

-       e.locker.Lock()
-       defer e.locker.Unlock()
+       e.locker.RLock()
        if _, ok := e.m[key]; ok {
+               e.locker.RUnlock()
                return e.m[key]
        } else {
+               e.locker.RUnlock()
                res := e.Enforcer.Enforce(rvals...)
+               e.locker.Lock()
                e.m[key] = res
+               e.locker.Unlock()
                return res
        }
 }
```

I see:

```
go test -cpu 4 -bench BenchmarkCachedRBACModelMediumParallel                                                                                                        
2019/04/25 19:20:49 Start automatically load policy
2019/04/25 19:20:49 Stop automatically load policy
2019/04/25 19:20:49 Start automatically load policy
2019/04/25 19:20:49 Model:
2019/04/25 19:20:49 r.r: sub, obj, act
2019/04/25 19:20:49 p.p: sub, obj, act
2019/04/25 19:20:49 e.e: some(where (p_eft == allow))
2019/04/25 19:20:49 m.m: r_sub == p_sub && r_obj == p_obj && r_act == p_act
2019/04/25 19:20:49 Policy:
2019/04/25 19:20:49 p: sub, obj, act: [[alice data1 read] [bob data2 write]]
2019/04/25 19:20:49 Request: alice, data1, read ---> true
2019/04/25 19:20:49 Request: alice, data1, write ---> false
2019/04/25 19:20:49 Request: alice, data2, read ---> false
2019/04/25 19:20:49 Request: alice, data2, write ---> false
2019/04/25 19:20:49 Request: bob, data1, read ---> false
2019/04/25 19:20:49 Request: bob, data1, write ---> false
2019/04/25 19:20:49 Request: bob, data2, read ---> false
2019/04/25 19:20:49 Request: bob, data2, write ---> true
2019/04/25 19:20:49 Stop automatically load policy
goos: linux
goarch: amd64
pkg: github.com/casbin/casbin
BenchmarkCachedRBACModelMediumParallel-4        10000000               226 ns/op
PASS
ok      github.com/casbin/casbin        5.593s
```

Roughly the same as using `sync.Map`. I haven't profiled memory usage to see if there are any differences.

Do you have a preference between `sync.RWMutex` or `sync.Map` given this?

**Comment by jszwedko** [comment]
Benchmarks with memory usage:

Using `sync.Mutex`:

```
go test -cpu 4 -bench BenchmarkCachedRBACModelMediumParallel -benchmem                                                                                                
2019/04/25 19:27:27 Start automatically load policy
2019/04/25 19:27:27 Stop automatically load policy
2019/04/25 19:27:27 Start automatically load policy
2019/04/25 19:27:27 Model:
2019/04/25 19:27:27 r.r: sub, obj, act
2019/04/25 19:27:27 p.p: sub, obj, act
2019/04/25 19:27:27 e.e: some(where (p_eft == allow))
2019/04/25 19:27:27 m.m: r_sub == p_sub && r_obj == p_obj && r_act == p_act
2019/04/25 19:27:27 Policy:
2019/04/25 19:27:27 p: sub, obj, act: [[alice data1 read] [bob data2 write]]
2019/04/25 19:27:27 Request: alice, data1, read ---> true
2019/04/25 19:27:27 Request: alice, data1, write ---> false
2019/04/25 19:27:27 Request: alice, data2, read ---> false
2019/04/25 19:27:27 Request: alice, data2, write ---> false
2019/04/25 19:27:27 Request: bob, data1, read ---> false
2019/04/25 19:27:27 Request: bob, data1, write ---> false
2019/04/25 19:27:27 Request: bob, data2, read ---> false
2019/04/25 19:27:27 Request: bob, data2, write ---> true
2019/04/25 19:27:28 Stop automatically load policy
goos: linux
goarch: amd64
pkg: github.com/casbin/casbin
BenchmarkCachedRBACModelMediumParallel-4         5000000               375 ns/op             128 B/op          4 allocs/op                                                                                         
PASS
ok      github.com/casbin/casbin        5.450s
```

Using `sync.RWMutex`:

```
go test -cpu 4 -bench BenchmarkCachedRBACModelMediumParallel -benchmem
2019/04/25 19:26:25 Start automatically load policy
2019/04/25 19:26:25 Stop automatically load policy
2019/04/25 19:26:25 Start automatically load policy
2019/04/25 19:26:25 Model:
2019/04/25 19:26:25 p.p: sub, obj, act
2019/04/25 19:26:25 e.e: some(where (p_eft == allow))
2019/04/25 19:26:25 m.m: r_sub == p_sub && r_obj == p_obj && r_act == p_act
2019/04/25 19:26:25 r.r: sub, obj, act
2019/04/25 19:26:25 Policy:
2019/04/25 19:26:25 p: sub, obj, act: [[alice data1 read] [bob data2 write]]
2019/04/25 19:26:25 Request: alice, data1, read ---> true
2019/04/25 19:26:25 Request: alice, data1, write ---> false
2019/04/25 19:26:25 Request: alice, data2, read ---> false
2019/04/25 19:26:25 Request: alice, data2, write ---> false
2019/04/25 19:26:25 Request: bob, data1, read ---> false
2019/04/25 19:26:25 Request: bob, data1, write ---> false
2019/04/25 19:26:25 Request: bob, data2, read ---> false
2019/04/25 19:26:25 Request: bob, data2, write ---> true
2019/04/25 19:26:25 Stop automatically load policy
goos: linux
goarch: amd64
pkg: github.com/casbin/casbin
BenchmarkCachedRBACModelMediumParallel-4         5000000               234 ns/op             128 B/op          4 allocs/op
PASS
ok      github.com/casbin/casbin        4.656s
```

Using `sync.Map`:

```
go test -cpu 4 -bench BenchmarkCachedRBACModelMediumParallel -benchmem                                                                                                
2019/04/25 19:28:08 Start automatically load policy
2019/04/25 19:28:08 Stop automatically load policy
2019/04/25 19:28:08 Start automatically load policy
2019/04/25 19:28:08 Model:
2019/04/25 19:28:08 r.r: sub, obj, act
2019/04/25 19:28:08 p.p: sub, obj, act
2019/04/25 19:28:08 e.e: some(where (p_eft == allow))
2019/04/25 19:28:08 m.m: r_sub == p_sub && r_obj == p_obj && r_act == p_act
2019/04/25 19:28:08 Policy:
2019/04/25 19:28:08 p: sub, obj, act: [[alice data1 read] [bob data2 write]]
2019/04/25 19:28:08 Request: alice, data1, read ---> true
2019/04/25 19:28:08 Request: alice, data1, write ---> false
2019/04/25 19:28:08 Request: alice, data2, read ---> false
2019/04/25 19:28:08 Request: alice, data2, write ---> false
2019/04/25 19:28:08 Request: bob, data1, read ---> false
2019/04/25 19:28:08 Request: bob, data1, write ---> false
2019/04/25 19:28:08 Request: bob, data2, read ---> false
2019/04/25 19:28:08 Request: bob, data2, write ---> true
2019/04/25 19:28:09 Stop automatically load policy
goos: linux
goarch: amd64
pkg: github.com/casbin/casbin
BenchmarkCachedRBACModelMediumParallel-4        10000000               248 ns/op             128 B/op          4 allocs/op                                                                                         
PASS
ok      github.com/casbin/casbin        5.959s
```

**Comment by jszwedko** [comment]
@vtolstov :+1: I force-pushed a commit switching to `sync.RWMutex`. I'm inclined to remove the benchmark I added and just replace the other tests with parallel execution. What do you think?

**Comment by jszwedko** [comment]
@vtolstov just circling back to this. Do you have an opinion on switching the benchmarks to run in parallel? Or should I perhaps just drop the added benchmark?

**Comment by vtolstov** [comment]
this is @hsluoyz can say, i'm not owner of repo. but i'm prefer to have benchmarks to be able to check in feature various improvements.

**Comment by hsluoyz** [comment]
Hi @jszwedko @vtolstov , I have looked through your conversation, and it seems that ``RWMutex`` is the fastest and best solution here. The code looks good to me so I'm going to merge it.

**Pull request merged**
