### PR TITLE
fix: add tests for SetFieldIndex&GetFieldIndex

### PR DESCRIPTION
**Pull request by JalinWang**
fix https://github.com/casbin/casbin/issues/1015#issuecomment-1171915149

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464 plz review

**Comment by hsluoyz** [comment]
@JalinWang fix:

image

**Comment by JalinWang** [comment]
> @JalinWang fix:
> 
> image

done

**Review by tangyang9464 — APPROVED** [review]
lgtm

**Comment by tangyang9464** [comment]
@JalinWang Please add the appropriate documentation for this. When users use RBAC or priority-related APIs, the default Index they should follow or how to customize FieldIndex

**Comment by JalinWang** [comment]
> @JalinWang Please add the appropriate documentation for this. When users use RBAC or priority-related APIs, the default Index they should follow or how to customize FieldIndex

ok

**Comment by JalinWang** [comment]
During the document composition, I add the additional test case of the customized priority token. 

image

**Comment by tangyang9464** [comment]
> During the document composition, I add the additional test case for the customized priority token.
> 
> image

It's ok.

**Comment by JalinWang** [comment]
@hsluoyz Is there anything more to do on this PR?

**Pull request merged**
