### PR TITLE
Adjust README for v2 

### PR DESCRIPTION
**Pull request by Fullstop000**

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @Fullstop000 , is it the right way to go get a v2 version? Any official docs?

**Comment by Fullstop000** [comment]
@hsluoyz Since the module name in `go.mod` is `github.com/casbin/casbin/v2`, we should use `go get github.com/casbin/casbin/v2` for the latest version following the rules in https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

And `go get github.com/casbin/casbin` will pull the last version in `v1.*.*`

**Comment by hsluoyz** [comment]
image

It's not working.

**Comment by Fullstop000** [comment]
It's strange. Do you enable the vgo? 

I ran the commands below:
```shell
go get github.com/casbin/casbin/v2
go get github.com/casbin/casbin 
```

And the `go.mod` changed in my demo project: 
```
module casbin-demo

go 1.12

require (
	github.com/casbin/casbin v1.9.1 // indirect
	github.com/casbin/casbin/v2 v2.0.1 // indirect
)
```

**Comment by Fullstop000** [comment]
Same situation in `gorm-adapter`

image

**Comment by hsluoyz** [comment]
https://stackoverflow.com/questions/53872505/package-github-com-matcornic-hermes-v2-cannot-find-package-github-com-matcorni

**Comment by Fullstop000** [comment]
> https://stackoverflow.com/questions/53872505/package-github-com-matcornic-hermes-v2-cannot-find-package-github-com-matcorni

If you use `go get github.com/casbin/casbin`  under a go-module enabled project out of the GOPATH, it always pulls casbin v1.9.1. So I believe this is not the same situation.

**Pull request closed without merging**
