### PR TITLE
fix: LoadPolicy() does not reflect the latest results

### PR DESCRIPTION
**Pull request by PokIsemaine**
Fix: https://github.com/casbin/casbin/issues/1181
## Description:
https://github.com/casbin/casbin/issues/1181#issuecomment-1415122920

### CODE REVIEW

**Comment by xingzem** [comment]
Hi, @PokIsemaine, @hsluoyz,   one issue I met is the enforcer.getFilteredNamedGroupingPolicy() does not give me the latest results in DB in my first call to this function. And the second call would reflect the correct result. Thinking it might be a cache mismatch with storage. I tried to add enforcer.loadPolicy() before the above function. The same issue still persists. I have tried the latest version here: https://central.sonatype.com/artifact/org.casbin/jcasbin/1.32.2/versions. Could you help with some comments on this? Thanks.

**Comment by PokIsemaine** [comment]
@xingzem Thanks for your feedback! Could you provide a code demo to reproduce this issue? This helps us confirm if they are the same issue and fix the problem. If convenient, you can create a new issue and describe it in detail in the issue.

**Comment by hsluoyz** [comment]
@xingzem which Casbin are you using? Go or Java?

**Comment by xingzem** [comment]
Hi @hsluoyz , we are using java. @PokIsemaine I am not sure whether I can get a demo out as I am not familiar how to set up the environment to run casbin separately. Let me check that though. 
The code we have right now is as belows: 
```
  @Override
  @Synchronized
  public List<User> getUsers(@Nonnull final String role, @Nonnull final String domain) {
    final List<User> users = new ArrayList<>();
    enforcer.loadPolicy();
    final List<List<String>> policies =
        enforcer.getFilteredNamedGroupingPolicy(GROUPING.toString(), 0, "", role, domain);

    for (final List<String> policy : policies) {
      users.add(toUser(policy));
    }

    return users;
  }
```
We have run into the issue of mismatch between cache memory and disk memory. The loadPolicy() was used to solve that issue. However, adding loadPolicy() does not seem to help. We still need two calls to this function to get fresh results from DB regardless whether loadPolicy() is used or not.

**Comment by hsluoyz** [comment]
@xingzem 

1. Create an issue instead of commenting in closed PR
2. Go to jCasbin repo instead of Golang Casbin
3. Loading policy is highly related to the adapter you used. Name your adapter, also try to switch to another adapter to see if issue exists

This PR will be locked to avoid distraction.

**Pull request merged**
