### PR TITLE
fix: roles with domain pattern build error

### PR DESCRIPTION
**Pull request by tangyang9464**
Signed-off-by: tangyang9464 <tangyang9464@163.com>

fix: #855

### CODE REVIEW

**Comment by tangyang9464** [comment]
https://github.com/casbin/casbin/blob/b6f62112061bd1b6b0163e4428423dac3cb4e092/rbac/default-role-manager/role_manager.go#L100-L103

Ideally, the ``patternDomain`` should contain all domains that meet the requirements.But when initializing for the first time, ``getPatternDomain`` can‘t get correct result.
for example:
```
g, user, admin, dom1
g, admin, super, *
```
Follow this method，the role inheritance shoule be
```
dom1::user --> dom1::admin
*::user --> *::admin

*::admin --> *::super
dom1::admin --> dom1::super
```
But now
```
dom1::user --> dom1::admin
*::admin --> *::super
```
Therefore, the simpler solution is to call ``e.model.BuildRoleLinks(e.rmMap)`` again after adding ``AddNamedDomainMatchingFunc``

**Comment by sagilio** [comment]
This is a little enhance, We can call `e.BuildRoleLinks()` manually, but this issue is about another error.

We can use user sample to test directly:
```go
func Test855Model(t *testing.T) {
	e, _ := NewEnforcer("examples/855.conf", "examples/855.csv")
	e.AddNamedDomainMatchingFunc("g", "KeyMatch", util.KeyMatch)
	testDomainEnforce(t, e, "user||1", "tenant||1", "menu||2", "*", true)    // 618L
	_ = e.BuildRoleLinks()
	testDomainEnforce(t, e, "user||1", "tenant||1", "menu||2", "*", true)
	testDomainEnforce(t, e, "user||1", "tenant||2", "menu||2", "*", false)   // 621L
}
```
The output is:
```
=== RUN   Test855Model
    model_test.go:618: user||1, tenant||1, menu||2, *: false, supposed to be true
    model_test.go:621: user||1, tenant||2, menu||2, *: true, supposed to be false
--- FAIL: Test855Model (0.00s)
```

**Comment by sagilio** [comment]
This reason about error return here:

```go
// testDomainEnforce(t, e, "user||1", "tenant||1", "menu||2", "*", true)   // 620L
HasLink: tenant||1::user||1 , tenant||1::role||1 , tenant||1 => false   // correct is true
HasLink: *::user||1 , *::role||1 , * => true    // correct is false
HasLink: tenant||1::user||1 , tenant||1::role||2 , tenant||1 => false   // correct is true
HasLink: *::user||1 , *::role||2 , * => true    // correct is false
... 

// testDomainEnforce(t, e, "user||1", "tenant||2", "menu||2", "*", false)   // 621L
HasLink: tenant||2::user||1 , tenant||2::role||1 , tenant||2 => false
HasLink: *::user||1 , *::role||1 , * => true    // correct is false
HasLink: tenant||2::user||1 , tenant||2::role||2 , tenant||2 => false
HasLink: *::user||1 , *::role||2 , * => true    // correct is false
...

**Comment by tangyang9464** [comment]
@sagilio I know the cause of the error. I think the current default_role_manager code design has big flaws.It makes me feel weird.Let me think again

**Pull request closed without merging**
