### PR TITLE
fix: Improve logger for management api

### PR DESCRIPTION
**Pull request by dovics**
Signed-off-by: dovics <wrs369@163.com>
fix: https://github.com/casbin/casbin/issues/581

### CODE REVIEW

**Comment by nodece** [comment]
Looks good to me, @hsluoyz, @GopherJ please take a look.

**Review by nodece — APPROVED** [review]

**Comment by GopherJ** [comment]
https://github.com/casbin/casbin/pull/591/files#diff-72816617037c9418525dfa491f4c5f77L52-L66

I have a feeling that this place will be buggy. How will it handle ABAC struct?

For example, if I enforce two times:

1. enforce(Person {name: "alice"}, "data1", "read")
2. enforce(Person {name: "bob"}, "data1", "read")

It seems the cache key will be the same, because it'll skip `Person{..}` which is not a `string`, @nodece @dovics How do you think?

**Comment by GopherJ** [comment]
Ok sorry I understood it'll not use cache if ABAC is founded

**Review by GopherJ — APPROVED** [review]

**Comment by dovics** [comment]
> Why no use defer in this case to claim ABAC is not cached? Currently if it's not cached then there is no log. Do we need a log when it's not cached?

There will be a log here, it comes from https://github.com/casbin/casbin/blob/master/enforcer.go#L570

**Pull request merged**
