### PR TITLE
feat: improve CachedEnforcer

### PR DESCRIPTION
**Pull request by alikhanz**
Fix: https://github.com/casbin/casbin/issues/927

@hsluoyz also i'm added redis cache implementation, but i dont know how to create new repositories :) Can you review, and prompt how i can add this implementation to your project?
https://github.com/alikhanz/casbin-cache-redis

### CODE REVIEW

**Review by sagilio — CHANGES_REQUESTED** [review]
Why change bool to bytes?

**Comment by alikhanz** [comment]
> Why change bool to bytes?

Hello.
Because `Cache` interface is more general, than the `enforce` response result. In future you can store in this cache any data you need. 
We can declare other interface, specific for `enforce` response, but i think this is unnecessary

**Comment by alikhanz** [comment]
Are we waiting for something?

**Comment by sagilio** [comment]
> > Why change bool to bytes?
> 
> Hello, @sagilio. Because `Cache` interface is more general, than the `enforce` response result. In future you can store in this cache any data you need. We can declare other interface, specific for `enforce` response, but i think this is unnecessary

@hsluoyz @nodece Any comment about this? I think different caches should have different interfaces, instead of using a common interface to store all cache structs.
For example, Casbin.NET has four different caches：
https://github.com/sagilio/Casbin.NET/tree/feat%23229/NetCasbin/Abstractions/Caching
image

**Comment by alikhanz** [comment]
> > > Why change bool to bytes?
> > 
> > 
> > Hello, @sagilio. Because `Cache` interface is more general, than the `enforce` response result. In future you can store in this cache any data you need. We can declare other interface, specific for `enforce` response, but i think this is unnecessary
> 
> @hsluoyz @nodece Any comment about this? I think different caches should have different interfaces, instead of using a common interface to store all cache structs. For example, Casbin.NET has four different caches： https://github.com/sagilio/Casbin.NET/tree/feat%23229/NetCasbin/Abstractions/Caching image

Yeah, it's good point, but see how Casbin.NET interfaces was defined:
`public interface IEnforceCache` - its specific interface, for specific method, and usecase.
As i said, we can add more interfaces for specific cache operations, if it really matters, but basic we need `cache.Cache` interface for using it in other implementations.

**Comment by alikhanz** [comment]
And more: 
I think we must more improvements in cache invalidation logic. 
Because current implementation works badly in RBAC requests. after changing the user's role, the cache will not be invalidated.
Now I have no idea how to fix it correctly. 
As an idea: we can add cache tags for subjects, and drop cache by this tags after changing roles.

**Comment by alikhanz** [comment]
Hi, @sagilio 
Unfortunately i ran into a lot of other problems with cache enforcer, as a result we can't continue to use casbin in our project due to perfomance and issues with cache enforcer, and i will not continue to support this PR, we can close it, i think.
P.S. Im signed CLA, but checks still not updated. After "recheck" too.

**Pull request closed without merging**
