### PR TITLE
fix: improve KeyMatch method to avoid endless loop

### PR DESCRIPTION
**Pull request by techoner**
fix: improve KeyMatch method to avoid endless loop(#447).

### CODE REVIEW

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@techoner Correct usage:
```
git add -A
git commit -m "fix: improve KeyMatch method to avoid endless loop"
```

**Comment by techoner** [comment]
@nodece So, how to link to issues?

**Comment by nodece** [comment]
> @nodece So, how to link to issues?

This is correct 
> fix: improve KeyMatch method to avoid endless loop(#447).

**Pull request merged**
