### PR TITLE
 fix:concurrent race when LoadPolicy is called

### PR DESCRIPTION
**Pull request by maocaicai**
Fix: https://github.com/casbin/casbin/issues/1116

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Abingcbc @imp2002 plz review

**Comment by sasakiyori** [comment]
excuse me why this PR is closed? @maocaicai

**Comment by maocaicai** [comment]
I changed a issue： https://github.com/casbin/casbin/issues/1107

**Comment by maocaicai** [comment]
new pr：https://github.com/casbin/casbin/pull/1141

**Comment by hsluoyz** [comment]
@sasakiyori the branch has been replaced so we no longer see the original content of this PR. The original PR cannot fix the issue so it's not merged

**Pull request closed without merging**
