### PR TITLE
Improvement/stop using NewModel constructor

### PR DESCRIPTION
**Pull request by obashistu**
The misplaced and strange NewModel constructor (it panics and is only ever used to differentiate between a filepath and a text) in enforcer can be bypassed entirely by using the safer model load functions dependent on whether it's from a path or a string. 

Since it's public the function remains but the logic therein is weird.

### CODE REVIEW

**Comment by hsluoyz** [comment]
Similar to my previous suggestion.

**Comment by obashistu** [comment]
Not to worry. Looking at the code we wont progress our project using Casbin. Closed all open PR's.

Have a good day.

**Comment by vtolstov** [comment]
@obashistu what you want to use instead of casbin?

**Comment by obashistu** [comment]
Hi @vtolstov initially Casbin looked interesting but after reviewing the code of the Go implementation we decided it would be safer to write our own. One positive that came from looking at Casbin closely is that we've decided to use the awesome https://github.com/Knetic/govaluate library to implement flexible policies.

**Pull request closed without merging**
