### PR TITLE
fix: improve KeyMatch method to avoid endless loop

### LINKED ISSUE #447: I think we should improve KeyMatch method to avoid endless loop
In KeyMatch all use `for{}` loop
```go
	re := regexp.MustCompile(`(.*)\{[^/]+\}(.*)`)
	for {
		if !strings.Contains(key2, "/{") {
			break
		}

		key2 = re.ReplaceAllString(key2, "$1([^/]+)$2")
	}
```
But in this case, it will form an endless loop
```
testKeyMatch2(t, "/alice", "/:/id", true)
testKeyMatch3(t, "/myid/using/myresid", "/{id/using/{resId}", true)
testKeyMatch4(t, "/parent/123/child/123", "/parent/{i/d}/child/{i/d}", true)
```

### PR DESCRIPTION
**Pull request by techoner**
fix: #447, improve KeyMatch method to avoid endless loop.

### CODE REVIEW

**Comment by nodece** [comment]
Hi @techoner, We need follow semantic commit. 

Rewrite the commit like: `fix: improve KeyMatch method to avoid endless loop`.

**Comment by hsluoyz** [comment]
lgtm

**Comment by nodece** [comment]
Hi @hsluoyz @techoner,  semantic commit refers to git commit rather than PR title.

**Comment by nodece** [comment]
The RP cannot tigger a release.

**Comment by hsluoyz** [comment]
@nodece sorry. I have reverted the PR.

@techoner can you re-make a new PR?

**Comment by techoner** [comment]
OK.

**Pull request merged**
