### PR TITLE
fix: nil pointer panic with no role definition model

### PR DESCRIPTION
**Pull request by ccccrrrr**
fix: #1369

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MuZhou233 plz review

**Comment by hsluoyz** [comment]
@ccccrrrr plz fix linter:

image

**Comment by MuZhou233** [comment]
@ccccrrrr Seems you didn't fix all the functions affected. As I mentioned, this issue affects a wide range of functions.
Also I advise you to add tests for this issue. As an example, the following test still causing panic.

```go
func TestRoleAPI_withoutRoleDefinition(t *testing.T) {
	e, _ := NewEnforcer("examples/basic_model.conf", "examples/basic_policy.csv")

	_, _ = e.AddRoleForUser("alice", "data1_admin")
}
```

**Comment by hsluoyz** [comment]
@ccccrrrr replaced by: https://github.com/casbin/casbin/pull/1389

**Pull request closed without merging**
