### PR TITLE
fix: role inheritance fault

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

Fix: #855

### CODE REVIEW

**Comment by closetool** [comment]
@hsluoyz @tangyang9464 Changed a lot for next pr to support cross domain

**Comment by tangyang9464** [comment]
@closetool 
I still use #855 sample to test and found some errors which are same as #858
```
p, role||2, dom2, menu||2, *

g, role||5, role||2, tenant||1

g, user||1, role||5, *
g, user||2, role||5, dom2

r, user||2, dom2, menu||2, *  -->true, but should be false ?
```
More interestingly，I just exchange their order and the result is false
```
p, role||2, dom2, menu||2, *

g, user||2, role||5, dom2  // exchange order

g, role||5, role||2, tenant||1

g, user||1, role||5, *

r, user||2, dom2, menu||2, *  -->false
```
I think the reason is
```
g, role||5, role||2, tenant||1
g, user||1, role||5, *

The mapping relationship is
*
user||1  ->  role||5
role||5  ->  role||2   // This shouldn't exist

tenant||1
user||1  ->  role||5
role||5  ->  role||2
```

**Comment by closetool** [comment]
@tangyang9464 I test your case, but the result is `false`

**Comment by hsluoyz** [comment]
@ErikXu plz review

**Comment by tangyang9464** [comment]
@closetool
Different order will lead to different results，this error is the same as #701
```
g, user||1, role||5, *
g, role||5, role||2, tenant||1

g, role||5, role||2, tenant||1
g, user||1, role||5, *
```
It is caused by ``getPatternDomain`` method

**Comment by closetool** [comment]
@tangyang9464 OK, I have an idea, we build the whole relationship after adding links.
Then perhaps everything will be OK.

**Comment by sagilio** [comment]
In fact, Casbin.NET uses the same implementation as you now. but, It can not fix all errors.

This struct can only check whether has links on one domain (included pattern domain like `*`), at the single loop of `match domains`. Then independently handle the result of each loop (now the final result is determined by the first `true` like `allow override`).

So now we may return an error result when two roles/users have a link in more than one domain at the same time.

**Comment by ErikXu** [comment]
@hsluoyz I've changed my local codes and tried the new version of [role_manager.go](https://github.com/casbin/casbin/blob/9bbcbaf37c555cc59d4ff6433c1f9aabbce84ec5/rbac/default-role-manager/role_manager.go) in this pull request. But the result still seems to be incorrect. Did I miss any steps?
> @ErikXu plz review

**Comment by tangyang9464** [comment]
> @hsluoyz I've changed my local codes and tried the new version of [role_manager.go](https://github.com/casbin/casbin/blob/9bbcbaf37c555cc59d4ff6433c1f9aabbce84ec5/rbac/default-role-manager/role_manager.go) in this pull request. But the result still seems to be incorrect. Did I miss any steps?
> 
> > @ErikXu plz review

@Erikxu
you need call ``e.BuildRoleLinks()`` like this
```
e.AddNamedDomainMatchingFunc("g","",util.KeyMatch)
e.BuildRoleLinks()
```

**Comment by tangyang9464** [comment]
> @tangyang9464 OK, I have an idea, we build the whole relationship after adding links.
> Then perhaps everything will be OK.

@closetool maybe we can just call ``e.model.BuildRoleLinks(e.rmMap)`` instead of ``e.BuildRoleLinks()`` because ``e.BuildRoleLinks()`` will call ``rm.Clear()``.Then the error can be resloved

**Comment by closetool** [comment]
@sagilio @tangyang9464 I think @sagilio is right, perhaps I could not fix this bug. We need to clarify which is wild card and which is not.

**Comment by tangyang9464** [comment]
> @sagilio @tangyang9464 I think @sagilio is right, perhaps I could not fix this bug. We need to clarify which is wild card and which is not.

@closetool @sagilio I understand a little bit, but don't know the specific example.Can you show me a simple example?

**Comment by ErikXu** [comment]
I've tried again as you mentioned, and the result turns out to be correct now. Could you please help to estimate and approve this pull request ASAP. So I can use the new version directly. Thanks very much!

> @ErikXu
> you need call `e.BuildRoleLinks()` like this
> 
> ```
> e.AddNamedDomainMatchingFunc("g","",util.KeyMatch)
> e.BuildRoleLinks()
> ```

**Comment by tangyang9464** [comment]
> I've tried again as you mentioned, and the result turns out to be correct now. Could you please help to estimate and approve this pull request ASAP. So I can use the new version directly. Thanks very much!
> 
> > @ErikXu
> > you need call `e.BuildRoleLinks()` like this
> > ```
> > e.AddNamedDomainMatchingFunc("g","",util.KeyMatch)
> > e.BuildRoleLinks()
> > ```

@ErikXu now this PR still has some other bugs.

**Comment by ErikXu** [comment]
OK, I understand. Please keep going with your own schedule. I will continue watching this issue. Thanks!

> > I've tried again as you mentioned, and the result turns out to be correct now. Could you please help to estimate and approve this pull request ASAP. So I can use the new version directly. Thanks very much!
> > > @ErikXu
> > > you need call `e.BuildRoleLinks()` like this
> > > ```
> > > e.AddNamedDomainMatchingFunc("g","",util.KeyMatch)
> > > e.BuildRoleLinks()
> > > ```
> 
> @ErikXu now this PR still has some other bugs.

**Comment by closetool** [comment]
@tangyang9464 @sagilio This pr should fixed all known bugs, plz review

**Comment by hsluoyz** [comment]
@ErikXu

**Review by sagilio — APPROVED** [review]

**Comment by tangyang9464** [comment]
@ErikXu now you can just use it normally.don't need to call ``e.BuildRoleLinks()``

**Comment by ErikXu** [comment]
@hsluoyz @tangyang9464 I've checked the latest version. It works fine so far. Please help to approve the pull request or arrange a version release. Thanks very much!


> @ErikXu now you can just use it normally.don't need to call `e.BuildRoleLinks()`

**Pull request merged**
