### PR TITLE
fix: enforcer action changed after calling `LoadPolicy`(#748)

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

fix: #748

### CODE REVIEW

**Comment by closetool** [comment]
@hsluoyz @giefferre plz reiview

**Comment by hsluoyz** [comment]
@closetool can you explain what caused this bug and why made such change?

**Comment by closetool** [comment]
@hsluoyz sure
In previous code, calling `LoadPolicy` resulted in replacement of rolemanger, `DomainMatchingFunc` and `MatchingFunc` will be deleted too, so we have to reset matching function.
Now, I just call the `Clear` method, and matching function will be reversed.

**Comment by hsluoyz** [comment]
@closetool great, just as I expected in: https://github.com/casbin/casbin/issues/748#issuecomment-812523355

**Pull request merged**
