### PR TITLE
feat: support GetNamedRoleManager & SetNamedRoleManager

### LINKED ISSUE #1075: [Question] Role Manager with Resource Role
**Want to prioritize this issue? Try:**

[issuehunt-to-marktext](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I'm working with a resource role rbac model, so I need apis such as `e.GetResourcesForResourceRole()` and `e.GetResourceRolesForResource()`.
I check their counterparts for roles and users, they are implemented with role managers.
But after skim through the source code, I found no way of getting the role manager for resource roles. `rmMap` is not exported and `GetRoleManager` only returns the one for users and roles.
So I'm here to ask if there's another way to get the role manager for resource roles.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && regexMatch(r.act, p.act)
```

### PR DESCRIPTION
**Pull request by ChenHaolinOlym**
fix #1075

### CODE REVIEW

**Review by tangyang9464 — APPROVED** [review]
lgtm

**Comment by hsluoyz** [comment]
@ChenHaolinOlym plz sign CLA:

image

**Comment by ChenHaolinOlym** [comment]
> @ChenHaolinOlym plz sign CLA:
> 
> image

Done

**Comment by hsluoyz** [comment]
@ChenHaolinOlym plz also add new APIs to: https://github.com/casbin/casbin.io

**Pull request merged**
