### PR TITLE
feat: support temporal roles model

### PR DESCRIPTION
**Pull request by PokIsemaine**
fix: https://github.com/casbin/casbin/issues/1259

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tony-spark plz review

**Comment by hsluoyz** [comment]
@PokIsemaine plz add docs

**Comment by nickcruess-soda** [comment]
I'd also be interested in seeing some documentation for this feature. We recently tried to upgrade from casbin/v2 2.73.1 to 2.75.1 and are now encountering errors with enforcer creation. After some digging we believe our existing `model.conf` is incompatible with this change, but we're not sure how. A little documentation would be very helpful.

**Comment by hsluoyz** [comment]
@nickcruess-soda docs has been added, see: https://github.com/casbin/casbin-website-v2/pull/204/files

**Comment by PokIsemaine** [comment]
@nickcruess-soda you can pay attention to the new test cases related to temporary role in the model_test.go

**Comment by nickcruess-soda** [comment]
Noted, will do. Thanks all

**Comment by thnt** [comment]
this breaks https://github.com/casbin/zap-logger

**Comment by hsluoyz** [comment]
@thnt can you create a new issue and provide more details like versions, error logs?

**Pull request merged**
