### PR TITLE
add support for glob operator

### PR DESCRIPTION
**Pull request by dafanasiev**
I think that glob operator more simple than regex for end users. Can u add it?

### CODE REVIEW

**Comment by slaskis** [comment]
Would it work as well with the built in https://golang.org/pkg/path/#Match and thus avoid another dependency?

**Comment by dafanasiev** [comment]
`path.Match` doesn't support "double-start" (`**`) operator, and support only `/` as separator.

**Comment by hsluoyz** [comment]
I agree with @slaskis , is there a way to avoid another dependency? like implementing it with one or several source files? Casbin is a library which will be used by other projects, so I keep the size of dependencies as small as possible. Currently, Casbin only depends on ``govaluate``, which is the expression interpreter.

**Comment by Pokerkoffer** [comment]
Any updates on this?

**Comment by hsluoyz** [comment]
@Pokerkoffer how to avoid another dependency?

**Comment by hsluoyz** [comment]
I'm revisiting this PR. How many people are there that need glob as built-in function?

**Comment by mousedownmike** [comment]
Would it be possible to use the [path.Match()](https://golang.org/pkg/path/#Match) in lieu of `globmatch`?

I come from a Spring Security background where they make heavy use of "Ant Style" [path matching](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html).  That level of complexity can be problematic in a security situation but I think some level of globbing would be useful for broad controls of REST APIs.

**Comment by hsluoyz** [comment]
I have asked the Golang community about built-in glob support: https://github.com/golang/go/issues/37964

**Comment by hsluoyz** [comment]
Finally, a built-in glob matching is integrated into Casbin: https://github.com/casbin/casbin/pull/397

So I will close this one now. Let me know if there are any questions.

**Pull request closed without merging**
